<#
.SYNOPSIS
    Regenerate .lcscore/state.md from git log --grep="SRC-"
.DESCRIPTION
    Run when state.md is inconsistent with CONTEXT.md.
    Extracts all SRC- tagged commits and writes a markdown table.
#>

$projectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$stateFile = Join-Path $projectRoot ".lcscore\state.md"

# YAML frontmatter
$frontmatter = @"
---
# Auto-generated by gen-state.ps1
# Do not edit manually — git log --grep="SRC-" is the source of truth
generated: $(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
---

"@

# Get SRC commits
$commits = git -C $projectRoot log --grep="SRC-" --format="| %h | %s | %ai |" --all

$content = $frontmatter + $commits + "`n"
Set-Content -Path $stateFile -Value $content -NoNewline

Write-Host "state.md regenerated from $((git -C $projectRoot log --grep="SRC-" --oneline --all).Count) SRC commits"
